# This is a basic workflow to help you get started with Actions

name: StoryAR-backend-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Connect to server using ssh
        run: |
          eval `ssh-agent`
          mkdir -p ~/.ssh chmod 600 ~/.ssh/id_rsa && chmod 700 ~/.ssh
          ssh-add - <<< "${{secrets.SERVER_PRIVATE_KEY}}"
          ssh-keyscan -t rsa ec2-13-210-139-210.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts
          ssh ubuntu@ec2-13-210-139-210.ap-southeast-2.compute.amazonaws.com


      # Runs a set of commands using the runners shell
      - name: Update changes
        run: |
          git pull

      # - name: Check
      #   run: |
      #     pm2 status
      
      # Restart application
      # - name: Restart application
      #   run: pm2 restart Story-AR-backend
