# This is a basic workflow to help you get started with Actions

name: StoryAR-backend-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [14.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Generate ENV file
      run: cp .env.example .env

    - name: SSH Deployment for latest  
      uses: appleboy/ssh-action@master 
      with: 
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}   
        key: ${{ secrets.SERVER_PRIVATE_KEY }} 
        script: |
          cd story-ar/StoryAR-backend/
          sudo npm install pm2 -g
          git pull 
          npm run build
          sudo pm2 restart 1